#!/usr/bin/env bash
# WARNING: This script assumes CMake 2.8.4+ and GCC/MinGW compiler is installed and available in system PATH.
# Copyright (C) 2013 LuaDist
# Redistribution and use of this file is allowed according to the terms of the MIT license.
# For details see the COPYRIGHT file distributed with LuaDist.
# Please note that the package source code is licensed under its own license.

REPO=`dirname "$(cd ${0%/*} && echo $PWD/${0##*/})"`
BOOT=$REPO/_bootstrap
BUILD=$BOOT/tmp
LUADIST="$BOOT/bin/lua $BOOT/lib/lua/luadist.lua"
INSTALL=$REPO/_install

echo "## This will build some LuaDist components TWO times!"

mkdir -p "$BUILD" && cd "$BUILD" && cmake "$REPO" -DCMAKE_INSTALL_PREFIX="$BOOT"
if [ "$?" != "0" ]; then
  echo "## Failed to prepare CMake build" >&2
  exit 1
fi
cmake --build "$BUILD" --target install -- -j6
if [ "$?" != "0" ]; then
  echo "## Failed to build using CMake" >&2
  exit 1
fi

echo "## Bootstrap done, building LuaDist using LuaDist"

$LUADIST "$INSTALL" install "$@" luadist2
if [ "$?" != "0" ]; then
  echo "## Failed to install LuaDist using LuaDist" >&2
  exit 1
fi

echo "## LuaDist is now built and can be found in the $INSTALL"
